(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good Morning Karenb, Welcome to Coot. 0.6.2 (revision 3562)  [with guile 1.8.7 embedded] [with python 2.6.0 embedded]")
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 10.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-maps 180.30)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(set-display-intro-string "Good morning ,,,. Welcome to Coot")
(set-display-lists-for-maps 0)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 10.00)
(set-swap-difference-map-colours 0)
(set-colour-map-rotation-for-maps 180.30)
(set-active-map-drag-flag 1)
(set-idle-function-rotate-angle  1.00)
(filter-fileselection-filenames-state)
(get-active-map-drag-flag)
(use-graphics-interface-state)
(get-eds-pdb-and-mtz "3eck")
(handle-read-draw-molecule-with-recentre "coot-download/pdb3eck.ent" 1)
(make-and-draw-map "coot-download/3eck_sigmaa.mtz" "2FOFCWT" "PH2FOFCWT" "" 0 0)
(make-and-draw-map "coot-download/3eck_sigmaa.mtz" "FOFCWT" "PHFOFCWT" "" 0 1)
(graphics-general-key-press-hook 65363)
(set-go-to-atom-molecule 0)
(update-go-to-atom-window-on-other-molecule-chosen)
(command-in-path? *probe-command*)
(command-in-path? *probe-command*)
(command-in-path? *probe-command*)
(set-filter-fileselection-filenames 0)
(unset-sticky-sort-by-date)
(set-colour-map-rotation-on-read-pdb 21.00)
(set-colour-map-rotation-on-read-pdb-c-only-flag 1)
(set-density-size 10.00)
(set-colour-map-rotation-for-maps 180.30)
(set-idle-function-rotate-angle  1.00)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 81)
(graphics-general-key-press-hook 81)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 81)
(graphics-general-key-press-hook 81)
(graphics-general-key-press-hook 81)
(graphics-general-key-press-hook 81)
(graphics-general-key-press-hook 81)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 113)
(graphics-general-key-press-hook 119)
(command-in-path? *probe-command*)
(command-in-path? *probe-command*)
(command-in-path? *probe-command*)
(command-in-path? *probe-command*)
(command-in-path? *probe-command*)
(first-coords-imol)
(get-refmac-version)
(set-refmac-molecule 0)
(get-refmac-version)
(command-in-path? *probe-command*)
(setup-auto-fit-rotamer 1)
(setup-auto-fit-rotamer 0)
(coot-checked-exit 0)
(clear-backups-maybe)
(stereo-mode-state)
(stereo-mode-state)
(save-state)
