filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good Morning Karenb, Welcome to Coot. 0.6.2 (revision 3562)  [with guile 1.8.7 embedded] [with python 2.6.0 embedded]")
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (10.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_maps (180.30)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
set_display_intro_string ("Good morning ,,,. Welcome to Coot")
set_display_lists_for_maps (0)
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (10.00)
set_swap_difference_map_colours (0)
set_colour_map_rotation_for_maps (180.30)
set_active_map_drag_flag (1)
set_idle_function_rotate_angle ( 1.00)
filter_fileselection_filenames_state ()
get_active_map_drag_flag ()
use_graphics_interface_state ()
;; # DIRECT SCHEME ((get-eds-pdb-and-mtz "3eck"))
handle_read_draw_molecule_with_recentre ("coot-download/pdb3eck.ent", 1)
make_and_draw_map ("coot-download/3eck_sigmaa.mtz", "2FOFCWT", "PH2FOFCWT", "", 0, 0)
make_and_draw_map ("coot-download/3eck_sigmaa.mtz", "FOFCWT", "PHFOFCWT", "", 0, 1)
;; # DIRECT SCHEME ((graphics-general-key-press-hook 65363))
set_go_to_atom_molecule (0)
update_go_to_atom_window_on_other_molecule_chosen ()
;; # DIRECT SCHEME ((command-in-path? *probe-command*))
;; # DIRECT SCHEME ((command-in-path? *probe-command*))
;; # DIRECT SCHEME ((command-in-path? *probe-command*))
set_filter_fileselection_filenames (0)
unset_sticky_sort_by_date ()
set_colour_map_rotation_on_read_pdb (21.00)
set_colour_map_rotation_on_read_pdb_c_only_flag (1)
set_density_size (10.00)
set_colour_map_rotation_for_maps (180.30)
set_idle_function_rotate_angle ( 1.00)
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 81))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 81))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 81))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 81))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 81))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 81))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 81))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 113))
;; # DIRECT SCHEME ((graphics-general-key-press-hook 119))
;; # DIRECT SCHEME ((command-in-path? *probe-command*))
;; # DIRECT SCHEME ((command-in-path? *probe-command*))
;; # DIRECT SCHEME ((command-in-path? *probe-command*))
;; # DIRECT SCHEME ((command-in-path? *probe-command*))
;; # DIRECT SCHEME ((command-in-path? *probe-command*))
first_coords_imol ()
;; # DIRECT SCHEME ((get-refmac-version))
set_refmac_molecule (0)
;; # DIRECT SCHEME ((get-refmac-version))
;; # DIRECT SCHEME ((command-in-path? *probe-command*))
setup_auto_fit_rotamer (1)
setup_auto_fit_rotamer (0)
coot_checked_exit (0)
;; # DIRECT SCHEME ((clear-backups-maybe))
stereo_mode_state ()
stereo_mode_state ()
save_state ()
